/*
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.integrations.weather.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * ForecastDay
 */
public class ForecastDay {
  @JsonProperty("maxtemp_c")
  private BigDecimal maxtempC = null;

  @JsonProperty("maxtemp_f")
  private BigDecimal maxtempF = null;

  @JsonProperty("mintemp_c")
  private BigDecimal mintempC = null;

  @JsonProperty("mintemp_f")
  private BigDecimal mintempF = null;

  @JsonProperty("avgtemp_c")
  private BigDecimal avgtempC = null;

  @JsonProperty("avgtemp_f")
  private BigDecimal avgtempF = null;

  @JsonProperty("maxwind_mph")
  private BigDecimal maxwindMph = null;

  @JsonProperty("maxwind_kph")
  private BigDecimal maxwindKph = null;

  @JsonProperty("totalprecip_mm")
  private BigDecimal totalprecipMm = null;

  @JsonProperty("totalprecip_in")
  private BigDecimal totalprecipIn = null;

  @JsonProperty("avgvis_km")
  private BigDecimal avgvisKm = null;

  @JsonProperty("avgvis_miles")
  private BigDecimal avgvisMiles = null;

  @JsonProperty("avghumidity")
  private BigDecimal avghumidity = null;

  @JsonProperty("daily_will_it_rain")
  private Integer dailyWillItRain = null;

  @JsonProperty("daily_chance_of_rain")
  private BigDecimal dailyChanceOfRain = null;

  @JsonProperty("daily_will_it_snow")
  private Integer dailyWillItSnow = null;

  @JsonProperty("daily_chance_of_snow")
  private BigDecimal dailyChanceOfSnow = null;

  @JsonProperty("condition")
  private ForecastDayCondition condition = null;

  @JsonProperty("uv")
  private Integer uv = null;

  public ForecastDay maxtempC(BigDecimal maxtempC) {
    this.maxtempC = maxtempC;
    return this;
  }

  /**
   * Get maxtempC
   * @return maxtempC
   **/
  public BigDecimal getMaxtempC() {
    return this.maxtempC;
  }

  public void setMaxtempC(BigDecimal maxtempC) {
    this.maxtempC = maxtempC;
  }

  public ForecastDay maxtempF(BigDecimal maxtempF) {
    this.maxtempF = maxtempF;
    return this;
  }

  /**
   * Get maxtempF
   * @return maxtempF
   **/
  public BigDecimal getMaxtempF() {
    return this.maxtempF;
  }

  public void setMaxtempF(BigDecimal maxtempF) {
    this.maxtempF = maxtempF;
  }

  public ForecastDay mintempC(BigDecimal mintempC) {
    this.mintempC = mintempC;
    return this;
  }

  /**
   * Get mintempC
   * @return mintempC
   **/
  public BigDecimal getMintempC() {
    return this.mintempC;
  }

  public void setMintempC(BigDecimal mintempC) {
    this.mintempC = mintempC;
  }

  public ForecastDay mintempF(BigDecimal mintempF) {
    this.mintempF = mintempF;
    return this;
  }

  /**
   * Get mintempF
   * @return mintempF
   **/
  public BigDecimal getMintempF() {
    return this.mintempF;
  }

  public void setMintempF(BigDecimal mintempF) {
    this.mintempF = mintempF;
  }

  public ForecastDay avgtempC(BigDecimal avgtempC) {
    this.avgtempC = avgtempC;
    return this;
  }

  /**
   * Get avgtempC
   * @return avgtempC
   **/
  public BigDecimal getAvgtempC() {
    return this.avgtempC;
  }

  public void setAvgtempC(BigDecimal avgtempC) {
    this.avgtempC = avgtempC;
  }

  public ForecastDay avgtempF(BigDecimal avgtempF) {
    this.avgtempF = avgtempF;
    return this;
  }

  /**
   * Get avgtempF
   * @return avgtempF
   **/
  public BigDecimal getAvgtempF() {
    return this.avgtempF;
  }

  public void setAvgtempF(BigDecimal avgtempF) {
    this.avgtempF = avgtempF;
  }

  public ForecastDay maxwindMph(BigDecimal maxwindMph) {
    this.maxwindMph = maxwindMph;
    return this;
  }

  /**
   * Get maxwindMph
   * @return maxwindMph
   **/
  public BigDecimal getMaxwindMph() {
    return this.maxwindMph;
  }

  public void setMaxwindMph(BigDecimal maxwindMph) {
    this.maxwindMph = maxwindMph;
  }

  public ForecastDay maxwindKph(BigDecimal maxwindKph) {
    this.maxwindKph = maxwindKph;
    return this;
  }

  /**
   * Get maxwindKph
   * @return maxwindKph
   **/
  public BigDecimal getMaxwindKph() {
    return this.maxwindKph;
  }

  public void setMaxwindKph(BigDecimal maxwindKph) {
    this.maxwindKph = maxwindKph;
  }

  public ForecastDay totalprecipMm(BigDecimal totalprecipMm) {
    this.totalprecipMm = totalprecipMm;
    return this;
  }

  /**
   * Get totalprecipMm
   * @return totalprecipMm
   **/
  public BigDecimal getTotalprecipMm() {
    return this.totalprecipMm;
  }

  public void setTotalprecipMm(BigDecimal totalprecipMm) {
    this.totalprecipMm = totalprecipMm;
  }

  public ForecastDay totalprecipIn(BigDecimal totalprecipIn) {
    this.totalprecipIn = totalprecipIn;
    return this;
  }

  /**
   * Get totalprecipIn
   * @return totalprecipIn
   **/
  public BigDecimal getTotalprecipIn() {
    return this.totalprecipIn;
  }

  public void setTotalprecipIn(BigDecimal totalprecipIn) {
    this.totalprecipIn = totalprecipIn;
  }

  public ForecastDay avgvisKm(BigDecimal avgvisKm) {
    this.avgvisKm = avgvisKm;
    return this;
  }

  /**
   * Get avgvisKm
   * @return avgvisKm
   **/
  public BigDecimal getAvgvisKm() {
    return this.avgvisKm;
  }

  public void setAvgvisKm(BigDecimal avgvisKm) {
    this.avgvisKm = avgvisKm;
  }

  public ForecastDay avgvisMiles(BigDecimal avgvisMiles) {
    this.avgvisMiles = avgvisMiles;
    return this;
  }

  /**
   * Get avgvisMiles
   * @return avgvisMiles
   **/
  public BigDecimal getAvgvisMiles() {
    return this.avgvisMiles;
  }

  public void setAvgvisMiles(BigDecimal avgvisMiles) {
    this.avgvisMiles = avgvisMiles;
  }

  public ForecastDay avghumidity(BigDecimal avghumidity) {
    this.avghumidity = avghumidity;
    return this;
  }

  /**
   * Get avghumidity
   * @return avghumidity
   **/
  public BigDecimal getAvghumidity() {
    return this.avghumidity;
  }

  public void setAvghumidity(BigDecimal avghumidity) {
    this.avghumidity = avghumidity;
  }

  public ForecastDay dailyWillItRain(Integer dailyWillItRain) {
    this.dailyWillItRain = dailyWillItRain;
    return this;
  }

  /**
   * Get dailyWillItRain
   * @return dailyWillItRain
   **/
  public Integer getDailyWillItRain() {
    return this.dailyWillItRain;
  }

  public void setDailyWillItRain(Integer dailyWillItRain) {
    this.dailyWillItRain = dailyWillItRain;
  }

  public ForecastDay dailyChanceOfRain(BigDecimal dailyChanceOfRain) {
    this.dailyChanceOfRain = dailyChanceOfRain;
    return this;
  }

  /**
   * Get dailyChanceOfRain
   * @return dailyChanceOfRain
   **/
  public BigDecimal getDailyChanceOfRain() {
    return this.dailyChanceOfRain;
  }

  public void setDailyChanceOfRain(BigDecimal dailyChanceOfRain) {
    this.dailyChanceOfRain = dailyChanceOfRain;
  }

  public ForecastDay dailyWillItSnow(Integer dailyWillItSnow) {
    this.dailyWillItSnow = dailyWillItSnow;
    return this;
  }

  /**
   * Get dailyWillItSnow
   * @return dailyWillItSnow
   **/
  public Integer getDailyWillItSnow() {
    return this.dailyWillItSnow;
  }

  public void setDailyWillItSnow(Integer dailyWillItSnow) {
    this.dailyWillItSnow = dailyWillItSnow;
  }

  public ForecastDay dailyChanceOfSnow(BigDecimal dailyChanceOfSnow) {
    this.dailyChanceOfSnow = dailyChanceOfSnow;
    return this;
  }

  /**
   * Get dailyChanceOfSnow
   * @return dailyChanceOfSnow
   **/
  public BigDecimal getDailyChanceOfSnow() {
    return this.dailyChanceOfSnow;
  }

  public void setDailyChanceOfSnow(BigDecimal dailyChanceOfSnow) {
    this.dailyChanceOfSnow = dailyChanceOfSnow;
  }

  public ForecastDay condition(ForecastDayCondition condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   **/
  public ForecastDayCondition getCondition() {
    return this.condition;
  }

  public void setCondition(ForecastDayCondition condition) {
    this.condition = condition;
  }

  public ForecastDay uv(Integer uv) {
    this.uv = uv;
    return this;
  }

  /**
   * Get uv
   * @return uv
   **/
  public Integer getUv() {
    return this.uv;
  }

  public void setUv(Integer uv) {
    this.uv = uv;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }
    ForecastDay forecastDay = (ForecastDay) o;
    return Objects.equals(this.maxtempC, forecastDay.maxtempC) &&
        Objects.equals(this.maxtempF, forecastDay.maxtempF) &&
        Objects.equals(this.mintempC, forecastDay.mintempC) &&
        Objects.equals(this.mintempF, forecastDay.mintempF) &&
        Objects.equals(this.avgtempC, forecastDay.avgtempC) &&
        Objects.equals(this.avgtempF, forecastDay.avgtempF) &&
        Objects.equals(this.maxwindMph, forecastDay.maxwindMph) &&
        Objects.equals(this.maxwindKph, forecastDay.maxwindKph) &&
        Objects.equals(this.totalprecipMm, forecastDay.totalprecipMm) &&
        Objects.equals(this.totalprecipIn, forecastDay.totalprecipIn) &&
        Objects.equals(this.avgvisKm, forecastDay.avgvisKm) &&
        Objects.equals(this.avgvisMiles, forecastDay.avgvisMiles) &&
        Objects.equals(this.avghumidity, forecastDay.avghumidity) &&
        Objects.equals(this.dailyWillItRain, forecastDay.dailyWillItRain) &&
        Objects.equals(this.dailyChanceOfRain, forecastDay.dailyChanceOfRain) &&
        Objects.equals(this.dailyWillItSnow, forecastDay.dailyWillItSnow) &&
        Objects.equals(this.dailyChanceOfSnow, forecastDay.dailyChanceOfSnow) &&
        Objects.equals(this.condition, forecastDay.condition) &&
        Objects.equals(this.uv, forecastDay.uv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.maxtempC, this.maxtempF, this.mintempC, this.mintempF, this.avgtempC, this.avgtempF, this.maxwindMph,
        this.maxwindKph, this.totalprecipMm, this.totalprecipIn, this.avgvisKm, this.avgvisMiles, this.avghumidity, this.dailyWillItRain,
        this.dailyChanceOfRain, this.dailyWillItSnow, this.dailyChanceOfSnow, this.condition, this.uv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastDay {\n");

    sb.append("    maxtempC: ").append(this.toIndentedString(this.maxtempC)).append("\n");
    sb.append("    maxtempF: ").append(this.toIndentedString(this.maxtempF)).append("\n");
    sb.append("    mintempC: ").append(this.toIndentedString(this.mintempC)).append("\n");
    sb.append("    mintempF: ").append(this.toIndentedString(this.mintempF)).append("\n");
    sb.append("    avgtempC: ").append(this.toIndentedString(this.avgtempC)).append("\n");
    sb.append("    avgtempF: ").append(this.toIndentedString(this.avgtempF)).append("\n");
    sb.append("    maxwindMph: ").append(this.toIndentedString(this.maxwindMph)).append("\n");
    sb.append("    maxwindKph: ").append(this.toIndentedString(this.maxwindKph)).append("\n");
    sb.append("    totalprecipMm: ").append(this.toIndentedString(this.totalprecipMm)).append("\n");
    sb.append("    totalprecipIn: ").append(this.toIndentedString(this.totalprecipIn)).append("\n");
    sb.append("    avgvisKm: ").append(this.toIndentedString(this.avgvisKm)).append("\n");
    sb.append("    avgvisMiles: ").append(this.toIndentedString(this.avgvisMiles)).append("\n");
    sb.append("    avghumidity: ").append(this.toIndentedString(this.avghumidity)).append("\n");
    sb.append("    dailyWillItRain: ").append(this.toIndentedString(this.dailyWillItRain)).append("\n");
    sb.append("    dailyChanceOfRain: ").append(this.toIndentedString(this.dailyChanceOfRain)).append("\n");
    sb.append("    dailyWillItSnow: ").append(this.toIndentedString(this.dailyWillItSnow)).append("\n");
    sb.append("    dailyChanceOfSnow: ").append(this.toIndentedString(this.dailyChanceOfSnow)).append("\n");
    sb.append("    condition: ").append(this.toIndentedString(this.condition)).append("\n");
    sb.append("    uv: ").append(this.toIndentedString(this.uv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

