/*
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.integrations.weather.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * ForecastHour
 */
public class ForecastHour {
  @JsonProperty("time_epoch")
  private Integer timeEpoch = null;

  @JsonProperty("time")
  private String time = null;

  @JsonProperty("temp_c")
  private BigDecimal tempC = null;

  @JsonProperty("temp_f")
  private BigDecimal tempF = null;

  @JsonProperty("is_day")
  private Integer isDay = null;

  @JsonProperty("condition")
  private ForecastCondition condition = null;

  @JsonProperty("wind_mph")
  private BigDecimal windMph = null;

  @JsonProperty("wind_kph")
  private BigDecimal windKph = null;

  @JsonProperty("wind_degree")
  private BigDecimal windDegree = null;

  @JsonProperty("wind_dir")
  private String windDir = null;

  @JsonProperty("pressure_mb")
  private BigDecimal pressureMb = null;

  @JsonProperty("pressure_in")
  private BigDecimal pressureIn = null;

  @JsonProperty("precip_mm")
  private BigDecimal precipMm = null;

  @JsonProperty("precip_in")
  private BigDecimal precipIn = null;

  @JsonProperty("humidity")
  private BigDecimal humidity = null;

  @JsonProperty("cloud")
  private BigDecimal cloud = null;

  @JsonProperty("feelslike_c")
  private BigDecimal feelslikeC = null;

  @JsonProperty("feelslike_f")
  private BigDecimal feelslikeF = null;

  @JsonProperty("windchill_c")
  private BigDecimal windchillC = null;

  @JsonProperty("windchill_f")
  private BigDecimal windchillF = null;

  @JsonProperty("heatindex_c")
  private BigDecimal heatindexC = null;

  @JsonProperty("heatindex_f")
  private BigDecimal heatindexF = null;

  @JsonProperty("dewpoint_c")
  private BigDecimal dewpointC = null;

  @JsonProperty("dewpoint_f")
  private BigDecimal dewpointF = null;

  @JsonProperty("will_it_rain")
  private Integer willItRain = null;

  @JsonProperty("chance_of_rain")
  private BigDecimal chanceOfRain = null;

  @JsonProperty("will_it_snow")
  private Integer willItSnow = null;

  @JsonProperty("chance_of_snow")
  private BigDecimal chanceOfSnow = null;

  @JsonProperty("vis_km")
  private BigDecimal visKm = null;

  @JsonProperty("vis_miles")
  private BigDecimal visMiles = null;

  @JsonProperty("gust_mph")
  private BigDecimal gustMph = null;

  @JsonProperty("gust_kph")
  private BigDecimal gustKph = null;

  @JsonProperty("uv")
  private Integer uv = null;

  public ForecastHour timeEpoch(Integer timeEpoch) {
    this.timeEpoch = timeEpoch;
    return this;
  }

  /**
   * Get timeEpoch
   * @return timeEpoch
   **/
  public Integer getTimeEpoch() {
    return this.timeEpoch;
  }

  public void setTimeEpoch(Integer timeEpoch) {
    this.timeEpoch = timeEpoch;
  }

  public ForecastHour time(String time) {
    this.time = time;
    return this;
  }

  /**
   * Get time
   * @return time
   **/
  public String getTime() {
    return this.time;
  }

  public void setTime(String time) {
    this.time = time;
  }

  public ForecastHour tempC(BigDecimal tempC) {
    this.tempC = tempC;
    return this;
  }

  /**
   * Get tempC
   * @return tempC
   **/
  public BigDecimal getTempC() {
    return this.tempC;
  }

  public void setTempC(BigDecimal tempC) {
    this.tempC = tempC;
  }

  public ForecastHour tempF(BigDecimal tempF) {
    this.tempF = tempF;
    return this;
  }

  /**
   * Get tempF
   * @return tempF
   **/
  public BigDecimal getTempF() {
    return this.tempF;
  }

  public void setTempF(BigDecimal tempF) {
    this.tempF = tempF;
  }

  public ForecastHour isDay(Integer isDay) {
    this.isDay = isDay;
    return this;
  }

  /**
   * Get isDay
   * @return isDay
   **/
  public Integer getIsDay() {
    return this.isDay;
  }

  public void setIsDay(Integer isDay) {
    this.isDay = isDay;
  }

  public ForecastHour condition(ForecastCondition condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   **/
  public ForecastCondition getCondition() {
    return this.condition;
  }

  public void setCondition(ForecastCondition condition) {
    this.condition = condition;
  }

  public ForecastHour windMph(BigDecimal windMph) {
    this.windMph = windMph;
    return this;
  }

  /**
   * Get windMph
   * @return windMph
   **/
  public BigDecimal getWindMph() {
    return this.windMph;
  }

  public void setWindMph(BigDecimal windMph) {
    this.windMph = windMph;
  }

  public ForecastHour windKph(BigDecimal windKph) {
    this.windKph = windKph;
    return this;
  }

  /**
   * Get windKph
   * @return windKph
   **/
  public BigDecimal getWindKph() {
    return this.windKph;
  }

  public void setWindKph(BigDecimal windKph) {
    this.windKph = windKph;
  }

  public ForecastHour windDegree(BigDecimal windDegree) {
    this.windDegree = windDegree;
    return this;
  }

  /**
   * Get windDegree
   * @return windDegree
   **/
  public BigDecimal getWindDegree() {
    return this.windDegree;
  }

  public void setWindDegree(BigDecimal windDegree) {
    this.windDegree = windDegree;
  }

  public ForecastHour windDir(String windDir) {
    this.windDir = windDir;
    return this;
  }

  /**
   * Get windDir
   * @return windDir
   **/
  public String getWindDir() {
    return this.windDir;
  }

  public void setWindDir(String windDir) {
    this.windDir = windDir;
  }

  public ForecastHour pressureMb(BigDecimal pressureMb) {
    this.pressureMb = pressureMb;
    return this;
  }

  /**
   * Get pressureMb
   * @return pressureMb
   **/
  public BigDecimal getPressureMb() {
    return this.pressureMb;
  }

  public void setPressureMb(BigDecimal pressureMb) {
    this.pressureMb = pressureMb;
  }

  public ForecastHour pressureIn(BigDecimal pressureIn) {
    this.pressureIn = pressureIn;
    return this;
  }

  /**
   * Get pressureIn
   * @return pressureIn
   **/
  public BigDecimal getPressureIn() {
    return this.pressureIn;
  }

  public void setPressureIn(BigDecimal pressureIn) {
    this.pressureIn = pressureIn;
  }

  public ForecastHour precipMm(BigDecimal precipMm) {
    this.precipMm = precipMm;
    return this;
  }

  /**
   * Get precipMm
   * @return precipMm
   **/
  public BigDecimal getPrecipMm() {
    return this.precipMm;
  }

  public void setPrecipMm(BigDecimal precipMm) {
    this.precipMm = precipMm;
  }

  public ForecastHour precipIn(BigDecimal precipIn) {
    this.precipIn = precipIn;
    return this;
  }

  /**
   * Get precipIn
   * @return precipIn
   **/
  public BigDecimal getPrecipIn() {
    return this.precipIn;
  }

  public void setPrecipIn(BigDecimal precipIn) {
    this.precipIn = precipIn;
  }

  public ForecastHour humidity(BigDecimal humidity) {
    this.humidity = humidity;
    return this;
  }

  /**
   * Get humidity
   * @return humidity
   **/
  public BigDecimal getHumidity() {
    return this.humidity;
  }

  public void setHumidity(BigDecimal humidity) {
    this.humidity = humidity;
  }

  public ForecastHour cloud(BigDecimal cloud) {
    this.cloud = cloud;
    return this;
  }

  /**
   * Get cloud
   * @return cloud
   **/
  public BigDecimal getCloud() {
    return this.cloud;
  }

  public void setCloud(BigDecimal cloud) {
    this.cloud = cloud;
  }

  public ForecastHour feelslikeC(BigDecimal feelslikeC) {
    this.feelslikeC = feelslikeC;
    return this;
  }

  /**
   * Get feelslikeC
   * @return feelslikeC
   **/
  public BigDecimal getFeelslikeC() {
    return this.feelslikeC;
  }

  public void setFeelslikeC(BigDecimal feelslikeC) {
    this.feelslikeC = feelslikeC;
  }

  public ForecastHour feelslikeF(BigDecimal feelslikeF) {
    this.feelslikeF = feelslikeF;
    return this;
  }

  /**
   * Get feelslikeF
   * @return feelslikeF
   **/
  public BigDecimal getFeelslikeF() {
    return this.feelslikeF;
  }

  public void setFeelslikeF(BigDecimal feelslikeF) {
    this.feelslikeF = feelslikeF;
  }

  public ForecastHour windchillC(BigDecimal windchillC) {
    this.windchillC = windchillC;
    return this;
  }

  /**
   * Get windchillC
   * @return windchillC
   **/
  public BigDecimal getWindchillC() {
    return this.windchillC;
  }

  public void setWindchillC(BigDecimal windchillC) {
    this.windchillC = windchillC;
  }

  public ForecastHour windchillF(BigDecimal windchillF) {
    this.windchillF = windchillF;
    return this;
  }

  /**
   * Get windchillF
   * @return windchillF
   **/
  public BigDecimal getWindchillF() {
    return this.windchillF;
  }

  public void setWindchillF(BigDecimal windchillF) {
    this.windchillF = windchillF;
  }

  public ForecastHour heatindexC(BigDecimal heatindexC) {
    this.heatindexC = heatindexC;
    return this;
  }

  /**
   * Get heatindexC
   * @return heatindexC
   **/
  public BigDecimal getHeatindexC() {
    return this.heatindexC;
  }

  public void setHeatindexC(BigDecimal heatindexC) {
    this.heatindexC = heatindexC;
  }

  public ForecastHour heatindexF(BigDecimal heatindexF) {
    this.heatindexF = heatindexF;
    return this;
  }

  /**
   * Get heatindexF
   * @return heatindexF
   **/
  public BigDecimal getHeatindexF() {
    return this.heatindexF;
  }

  public void setHeatindexF(BigDecimal heatindexF) {
    this.heatindexF = heatindexF;
  }

  public ForecastHour dewpointC(BigDecimal dewpointC) {
    this.dewpointC = dewpointC;
    return this;
  }

  /**
   * Get dewpointC
   * @return dewpointC
   **/
  public BigDecimal getDewpointC() {
    return this.dewpointC;
  }

  public void setDewpointC(BigDecimal dewpointC) {
    this.dewpointC = dewpointC;
  }

  public ForecastHour dewpointF(BigDecimal dewpointF) {
    this.dewpointF = dewpointF;
    return this;
  }

  /**
   * Get dewpointF
   * @return dewpointF
   **/
  public BigDecimal getDewpointF() {
    return this.dewpointF;
  }

  public void setDewpointF(BigDecimal dewpointF) {
    this.dewpointF = dewpointF;
  }

  public ForecastHour willItRain(Integer willItRain) {
    this.willItRain = willItRain;
    return this;
  }

  /**
   * Get willItRain
   * @return willItRain
   **/
  public Integer getWillItRain() {
    return this.willItRain;
  }

  public void setWillItRain(Integer willItRain) {
    this.willItRain = willItRain;
  }

  public ForecastHour chanceOfRain(BigDecimal chanceOfRain) {
    this.chanceOfRain = chanceOfRain;
    return this;
  }

  /**
   * Get chanceOfRain
   * @return chanceOfRain
   **/
  public BigDecimal getChanceOfRain() {
    return this.chanceOfRain;
  }

  public void setChanceOfRain(BigDecimal chanceOfRain) {
    this.chanceOfRain = chanceOfRain;
  }

  public ForecastHour willItSnow(Integer willItSnow) {
    this.willItSnow = willItSnow;
    return this;
  }

  /**
   * Get willItSnow
   * @return willItSnow
   **/
  public Integer getWillItSnow() {
    return this.willItSnow;
  }

  public void setWillItSnow(Integer willItSnow) {
    this.willItSnow = willItSnow;
  }

  public ForecastHour chanceOfSnow(BigDecimal chanceOfSnow) {
    this.chanceOfSnow = chanceOfSnow;
    return this;
  }

  /**
   * Get chanceOfSnow
   * @return chanceOfSnow
   **/
  public BigDecimal getChanceOfSnow() {
    return this.chanceOfSnow;
  }

  public void setChanceOfSnow(BigDecimal chanceOfSnow) {
    this.chanceOfSnow = chanceOfSnow;
  }

  public ForecastHour visKm(BigDecimal visKm) {
    this.visKm = visKm;
    return this;
  }

  /**
   * Get visKm
   * @return visKm
   **/
  public BigDecimal getVisKm() {
    return this.visKm;
  }

  public void setVisKm(BigDecimal visKm) {
    this.visKm = visKm;
  }

  public ForecastHour visMiles(BigDecimal visMiles) {
    this.visMiles = visMiles;
    return this;
  }

  /**
   * Get visMiles
   * @return visMiles
   **/
  public BigDecimal getVisMiles() {
    return this.visMiles;
  }

  public void setVisMiles(BigDecimal visMiles) {
    this.visMiles = visMiles;
  }

  public ForecastHour gustMph(BigDecimal gustMph) {
    this.gustMph = gustMph;
    return this;
  }

  /**
   * Get gustMph
   * @return gustMph
   **/
  public BigDecimal getGustMph() {
    return this.gustMph;
  }

  public void setGustMph(BigDecimal gustMph) {
    this.gustMph = gustMph;
  }

  public ForecastHour gustKph(BigDecimal gustKph) {
    this.gustKph = gustKph;
    return this;
  }

  /**
   * Get gustKph
   * @return gustKph
   **/
  public BigDecimal getGustKph() {
    return this.gustKph;
  }

  public void setGustKph(BigDecimal gustKph) {
    this.gustKph = gustKph;
  }

  public ForecastHour uv(Integer uv) {
    this.uv = uv;
    return this;
  }

  /**
   * Get uv
   * @return uv
   **/
  public Integer getUv() {
    return this.uv;
  }

  public void setUv(Integer uv) {
    this.uv = uv;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }
    ForecastHour forecastHour = (ForecastHour) o;
    return Objects.equals(this.timeEpoch, forecastHour.timeEpoch) &&
        Objects.equals(this.time, forecastHour.time) &&
        Objects.equals(this.tempC, forecastHour.tempC) &&
        Objects.equals(this.tempF, forecastHour.tempF) &&
        Objects.equals(this.isDay, forecastHour.isDay) &&
        Objects.equals(this.condition, forecastHour.condition) &&
        Objects.equals(this.windMph, forecastHour.windMph) &&
        Objects.equals(this.windKph, forecastHour.windKph) &&
        Objects.equals(this.windDegree, forecastHour.windDegree) &&
        Objects.equals(this.windDir, forecastHour.windDir) &&
        Objects.equals(this.pressureMb, forecastHour.pressureMb) &&
        Objects.equals(this.pressureIn, forecastHour.pressureIn) &&
        Objects.equals(this.precipMm, forecastHour.precipMm) &&
        Objects.equals(this.precipIn, forecastHour.precipIn) &&
        Objects.equals(this.humidity, forecastHour.humidity) &&
        Objects.equals(this.cloud, forecastHour.cloud) &&
        Objects.equals(this.feelslikeC, forecastHour.feelslikeC) &&
        Objects.equals(this.feelslikeF, forecastHour.feelslikeF) &&
        Objects.equals(this.windchillC, forecastHour.windchillC) &&
        Objects.equals(this.windchillF, forecastHour.windchillF) &&
        Objects.equals(this.heatindexC, forecastHour.heatindexC) &&
        Objects.equals(this.heatindexF, forecastHour.heatindexF) &&
        Objects.equals(this.dewpointC, forecastHour.dewpointC) &&
        Objects.equals(this.dewpointF, forecastHour.dewpointF) &&
        Objects.equals(this.willItRain, forecastHour.willItRain) &&
        Objects.equals(this.chanceOfRain, forecastHour.chanceOfRain) &&
        Objects.equals(this.willItSnow, forecastHour.willItSnow) &&
        Objects.equals(this.chanceOfSnow, forecastHour.chanceOfSnow) &&
        Objects.equals(this.visKm, forecastHour.visKm) &&
        Objects.equals(this.visMiles, forecastHour.visMiles) &&
        Objects.equals(this.gustMph, forecastHour.gustMph) &&
        Objects.equals(this.gustKph, forecastHour.gustKph) &&
        Objects.equals(this.uv, forecastHour.uv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.timeEpoch, this.time, this.tempC, this.tempF, this.isDay, this.condition, this.windMph, this.windKph,
        this.windDegree, this.windDir, this.pressureMb, this.pressureIn,
        this.precipMm, this.precipIn, this.humidity, this.cloud, this.feelslikeC, this.feelslikeF, this.windchillC, this.windchillF,
        this.heatindexC, this.heatindexF, this.dewpointC, this.dewpointF,
        this.willItRain, this.chanceOfRain, this.willItSnow, this.chanceOfSnow, this.visKm, this.visMiles, this.gustMph, this.gustKph,
        this.uv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastHour {\n");

    sb.append("    timeEpoch: ").append(this.toIndentedString(this.timeEpoch)).append("\n");
    sb.append("    time: ").append(this.toIndentedString(this.time)).append("\n");
    sb.append("    tempC: ").append(this.toIndentedString(this.tempC)).append("\n");
    sb.append("    tempF: ").append(this.toIndentedString(this.tempF)).append("\n");
    sb.append("    isDay: ").append(this.toIndentedString(this.isDay)).append("\n");
    sb.append("    condition: ").append(this.toIndentedString(this.condition)).append("\n");
    sb.append("    windMph: ").append(this.toIndentedString(this.windMph)).append("\n");
    sb.append("    windKph: ").append(this.toIndentedString(this.windKph)).append("\n");
    sb.append("    windDegree: ").append(this.toIndentedString(this.windDegree)).append("\n");
    sb.append("    windDir: ").append(this.toIndentedString(this.windDir)).append("\n");
    sb.append("    pressureMb: ").append(this.toIndentedString(this.pressureMb)).append("\n");
    sb.append("    pressureIn: ").append(this.toIndentedString(this.pressureIn)).append("\n");
    sb.append("    precipMm: ").append(this.toIndentedString(this.precipMm)).append("\n");
    sb.append("    precipIn: ").append(this.toIndentedString(this.precipIn)).append("\n");
    sb.append("    humidity: ").append(this.toIndentedString(this.humidity)).append("\n");
    sb.append("    cloud: ").append(this.toIndentedString(this.cloud)).append("\n");
    sb.append("    feelslikeC: ").append(this.toIndentedString(this.feelslikeC)).append("\n");
    sb.append("    feelslikeF: ").append(this.toIndentedString(this.feelslikeF)).append("\n");
    sb.append("    windchillC: ").append(this.toIndentedString(this.windchillC)).append("\n");
    sb.append("    windchillF: ").append(this.toIndentedString(this.windchillF)).append("\n");
    sb.append("    heatindexC: ").append(this.toIndentedString(this.heatindexC)).append("\n");
    sb.append("    heatindexF: ").append(this.toIndentedString(this.heatindexF)).append("\n");
    sb.append("    dewpointC: ").append(this.toIndentedString(this.dewpointC)).append("\n");
    sb.append("    dewpointF: ").append(this.toIndentedString(this.dewpointF)).append("\n");
    sb.append("    willItRain: ").append(this.toIndentedString(this.willItRain)).append("\n");
    sb.append("    chanceOfRain: ").append(this.toIndentedString(this.chanceOfRain)).append("\n");
    sb.append("    willItSnow: ").append(this.toIndentedString(this.willItSnow)).append("\n");
    sb.append("    chanceOfSnow: ").append(this.toIndentedString(this.chanceOfSnow)).append("\n");
    sb.append("    visKm: ").append(this.toIndentedString(this.visKm)).append("\n");
    sb.append("    visMiles: ").append(this.toIndentedString(this.visMiles)).append("\n");
    sb.append("    gustMph: ").append(this.toIndentedString(this.gustMph)).append("\n");
    sb.append("    gustKph: ").append(this.toIndentedString(this.gustKph)).append("\n");
    sb.append("    uv: ").append(this.toIndentedString(this.uv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

