/*
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.integrations.weather.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ForecastForecastday
 */
public class ForecastForecastday {
  @JsonProperty("date")
  private LocalDate date = null;

  @JsonProperty("date_epoch")
  private Integer dateEpoch = null;

  @JsonProperty("day")
  private ForecastDay day = null;

  @JsonProperty("astro")
  private ForecastAstro astro = null;

  @JsonProperty("hour")
  private List<ForecastHour> hour = null;

  public ForecastForecastday date(LocalDate date) {
    this.date = date;
    return this;
  }

  /**
   * Get date
   * @return date
   **/
  public LocalDate getDate() {
    return this.date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public ForecastForecastday dateEpoch(Integer dateEpoch) {
    this.dateEpoch = dateEpoch;
    return this;
  }

  /**
   * Get dateEpoch
   * @return dateEpoch
   **/
  public Integer getDateEpoch() {
    return this.dateEpoch;
  }

  public void setDateEpoch(Integer dateEpoch) {
    this.dateEpoch = dateEpoch;
  }

  public ForecastForecastday day(ForecastDay day) {
    this.day = day;
    return this;
  }

  /**
   * Get day
   * @return day
   **/
  public ForecastDay getDay() {
    return this.day;
  }

  public void setDay(ForecastDay day) {
    this.day = day;
  }

  public ForecastForecastday astro(ForecastAstro astro) {
    this.astro = astro;
    return this;
  }

  /**
   * Get astro
   * @return astro
   **/
  public ForecastAstro getAstro() {
    return this.astro;
  }

  public void setAstro(ForecastAstro astro) {
    this.astro = astro;
  }

  public ForecastForecastday hour(List<ForecastHour> hour) {
    this.hour = hour;
    return this;
  }

  public ForecastForecastday addHourItem(ForecastHour hourItem) {
    if (this.hour == null) {
      this.hour = new ArrayList<>();
    }
    this.hour.add(hourItem);
    return this;
  }

  /**
   * Get hour
   * @return hour
   **/
  public List<ForecastHour> getHour() {
    return this.hour;
  }

  public void setHour(List<ForecastHour> hour) {
    this.hour = hour;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }
    ForecastForecastday forecastForecastday = (ForecastForecastday) o;
    return Objects.equals(this.date, forecastForecastday.date) &&
        Objects.equals(this.dateEpoch, forecastForecastday.dateEpoch) &&
        Objects.equals(this.day, forecastForecastday.day) &&
        Objects.equals(this.astro, forecastForecastday.astro) &&
        Objects.equals(this.hour, forecastForecastday.hour);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.date, this.dateEpoch, this.day, this.astro, this.hour);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastForecastday {\n");

    sb.append("    date: ").append(this.toIndentedString(this.date)).append("\n");
    sb.append("    dateEpoch: ").append(this.toIndentedString(this.dateEpoch)).append("\n");
    sb.append("    day: ").append(this.toIndentedString(this.day)).append("\n");
    sb.append("    astro: ").append(this.toIndentedString(this.astro)).append("\n");
    sb.append("    hour: ").append(this.toIndentedString(this.hour)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

